
image:
  file: .gitpod.Dockerfile

tasks:
  - name: player-service-app
    before: |
      cd player-service
    init: mvn package -DskipTests
  - name: player-service-model
    before: |
      cd player-service-model
    init: pip3 install -r requirements.txt

ports:
  - port: 8080  # Port for player-service-app
    onOpen: open-preview
  - port: 5000  # Port for player-service-model
    onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot